apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-tls-argo
  issuerRef:
    name: argo-cd-issuer
    kind: Issuer
  commonName: argo.cloud-nation.club
  dnsNames:
  - argo.cloud-nation.club