apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-web-ui
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.org/client-max-body-size: 100M
spec:
  tls:
    - hosts:
      - cd.cloud-nation.club
      secretName: argocd-secret-cd
  rules:
  - host: cd.cloud-nation.club
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: 80