apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: argo-cd-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: support@virtocommerce.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          name: argo-cd-ui