apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-web-ui
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  tls:
    - hosts:
      - argo.cloud-nation.club
      secretName: argocd-secret
  rules:
  - host: argo.cloud-nation.club
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: https