apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argo-cd-ui
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/app-root: "/"
spec:
  # tls:
  #   - hosts:
  #     - argo.cloud-nation.club
  #     secretName: argocd-tls-argo
  rules:
  - host: argo.cloud-nation.club
    http:
      paths:
      - backend:
          serviceName: argocd-server
          servicePort: 80  
        path: /
        