apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:cloud-nation-developers, applications, get, dev-tenant/*, allow
    p, role:cloud-nation-developers, applications, sync, dev-tenant/*, allow 
    p, role:cloud-nation-developers, applications, delete, dev-tenant/*, allow
    p, role:cloud-nation-developers, applications, get, prod-tenant/*, allow
    p, role:cloud-nation-developers, applications, sync, prod-tenant/*, allow    
    p, role:cloud-nation-developers, clusters, get, *, allow
    g, cloud-nation:operations, role:admin
    g, cloud-nation:developers, role:cloud-nation-developers