apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:virto-developers, applications, get, tenant/*, allow
    p, role:virto-developers, applications, sync, tenant/*, allow 
    p, role:virto-developers, applications, delete, tenant/*, allow
    p, role:virto-developers, applications, get, demo-tenant/*, allow
    p, role:virto-developers, applications, sync, demo-tenant/*, allow    
    p, role:virto-developers, clusters, get, *, allow
    g, VirtoCommerce:Virto Operations, role:admin
    g, VirtoCommerce:Virto Commerce, role:virto-developers