apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: prod-tenant
  source:
    path: apps-config/overlays/prod
    repoURL: https://github.com/cloud-nation/apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-dev-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: dev-tenant
  source:
    path: apps-config/overlays/dev
    repoURL: https://github.com/cloud-nation/apps
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true            