apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-compute-resources
  namespace: dev
spec:
  hard:
    limits.memory: 2Gi
    pods: "8"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-compute-resources
  namespace: prod
spec:
  hard:
    limits.memory: 2Gi
    pods: "8"