apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 64Mi
    max:
      memory: 1Gi
    min:
      memory: 16Mi
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limit-range
  namespace: prod
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      memory: 64Mi
    max:
      memory: 1Gi
    min:
      memory: 16Mi
    type: Container  