apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
apiVersion: v1
kind: Namespace
metadata:
  name: qa
  annotations:
    argocd.argoproj.io/sync-wave: "-1"       
---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: hashicorp-vault
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: v1
kind: Namespace
metadata:
  name: saas
  annotations:
    argocd.argoproj.io/sync-wave: "-1"    
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: weave-scope
    annotations:
      argocd.argoproj.io/sync-wave: "-1" 
---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring
    annotations:
      argocd.argoproj.io/sync-wave: "-1"   

