apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-compute-resources
  namespace: dev
spec:
  hard:
    limits.memory: 4Gi
    pods: "20"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-compute-resources
  namespace: prod
spec:
  hard:
    limits.memory: 3Gi
    pods: "10"