apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    targetRevision: 9.8.0
    helm:
      parameters:
      - name: ingressClass.enabled
        value: 'true'
      - name: providers.kubernetesIngress.publishedService.enabled
        value: 'true'
    chart: traefik 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true